Fixed the error/warning functions also in the preloader script

diff --git a/zip-content/META-INF/com/google/android/update-binary b/zip-content/META-INF/com/google/android/update-binary
--- a/zip-content/META-INF/com/google/android/update-binary
+++ b/zip-content/META-INF/com/google/android/update-binary
@@ -54,6 +54,26 @@ disable_debug_log()
   DEBUG_LOG_ENABLED=0
 }
 
+_show_text_on_recovery()
+{
+  echo -e "ui_print $1\nui_print" >> $RECOVERY_PIPE
+}
+
+ui_error()
+{
+  ERROR_CODE=79
+  if test -n "$2"; then ERROR_CODE="$2"; fi
+  >&2 echo "ERROR ${ERROR_CODE}: $1"
+  _show_text_on_recovery "ERROR: $1"
+  exit "${ERROR_CODE}"
+}
+
+ui_warning()
+{
+  >&2 echo "WARNING: $1"
+  _show_text_on_recovery "WARNING: $1"
+}
+
 ui_msg()
 {
   echo -e "ui_print $1\nui_print" >> $RECOVERY_PIPE
@@ -63,14 +83,6 @@ ui_msg()
 ui_debug()
 {
   echo "$1"
-}
-
-ui_error()
-{
-  #>&2 echo "ERROR: $1"
-  ui_msg "ERROR: $1"
-  test -n "$2" && exit "$2"
-  exit 79
 }
 
 is_mounted()
