Minor changes

diff --git a/.github/workflows/auto-nightly.yml b/.github/workflows/auto-nightly.yml
--- a/.github/workflows/auto-nightly.yml
+++ b/.github/workflows/auto-nightly.yml
@@ -72,27 +72,33 @@ jobs:
         id: "info"
         run: |
           # Retrieving informations...
-          ZIP_FOLDER='${{ steps.build.outputs.ZIP_FOLDER }}'
-          : "${ZIP_FOLDER:?}" || exit "${?}"
+          test -n '${{ steps.build.outputs.ZIP_FOLDER }}' || exit 3
           ZIP_FILENAME='${{ steps.build.outputs.ZIP_FILENAME }}'
           ZIP_VERSION='${{ steps.build.outputs.ZIP_VERSION }}'
           ZIP_SHORT_COMMIT_ID='${{ steps.build.outputs.ZIP_SHORT_COMMIT_ID }}'
+          ZIP_IS_ALPHA='${{ steps.build.outputs.ZIP_IS_ALPHA }}'
           ZIP_BUILD_TYPE='${{ steps.build.outputs.ZIP_BUILD_TYPE }}'
           ZIP_BUILD_TYPE_SUPPORTED='${{ steps.build.outputs.ZIP_BUILD_TYPE_SUPPORTED }}'
-          ZIP_IS_ALPHA='${{ steps.build.outputs.ZIP_IS_ALPHA }}'
-          ZIP_SHA256='${{ steps.build.outputs.ZIP_SHA256 }}'
           ZIP_MD5='${{ steps.build.outputs.ZIP_MD5 }}'
+          ZIP_SHA256='${{ steps.build.outputs.ZIP_SHA256 }}'
           ZIP_ATTESTATION_URL='${{ steps.attest.outputs.attestation-url }}'
           # Displaying informations...
           printf '%s\n' "::notice::Filename: ${ZIP_FILENAME:-Missing}"
-          printf '%s\n' "::notice::Version: ${ZIP_VERSION:-Missing}"
-          printf '%s\n' "::notice::Short commit ID: ${ZIP_SHORT_COMMIT_ID:-Missing}"
-          printf '%s\n' "::notice::Build type: ${ZIP_BUILD_TYPE:?}"
+          printf '%s\n' "::notice::Version: ${ZIP_VERSION:?} - Short commit ID: ${ZIP_SHORT_COMMIT_ID:?} - Is alpha: ${ZIP_IS_ALPHA:?} - Build type: ${ZIP_BUILD_TYPE:?}"
+          if '${{ github.ref_name && github.ref_name != github.event.repository.default_branch }}'; then
+            ZIP_RETENTION_DAYS=30
+            printf '%s\n' '::notice::Branch: ${{ github.ref_name }}'
+          else
+            ZIP_RETENTION_DAYS=10
+          fi
           printf '%s\n' "::notice::Build type supported: ${ZIP_BUILD_TYPE_SUPPORTED:?}"
-          printf '%s\n' "::notice::Is alpha: ${ZIP_IS_ALPHA:-Missing}"
-          printf '%s\n' "::notice::SHA-256: ${ZIP_SHA256:-Missing}"
           printf '%s\n' "::notice::MD5: ${ZIP_MD5:-Missing}"
+          printf '%s\n' "::notice::SHA-256: ${ZIP_SHA256:-Missing}"
+          printf '%s\n' "::notice::Logs retention days: ${{ github.retention_days }}"
+          printf '%s\n' "::notice::Artifacts retention days: ${ZIP_RETENTION_DAYS:?}"
           printf '%s\n' "::notice::Attestation: ${ZIP_ATTESTATION_URL:-Missing}"
+          # Outputs
+          printf 'ZIP_RETENTION_DAYS=%s\n' "${ZIP_RETENTION_DAYS:?}" 1>> "${GITHUB_OUTPUT?}"
           # Preparing temp folder...
           export TMPDIR="${TMPDIR:-${RUNNER_TEMP:-${TMP:-${TEMP:-/tmp}}}}" || exit "${?}"
           our_tmp_dir="$(mktemp -d -t -- "RELEASE-${ZIP_IS_ALPHA:?}-XXXXXX")" || exit "${?}"
@@ -227,9 +233,10 @@ jobs:
         with:
           name: "${{ github.event.repository.name }} ${{ github.ref_name }} g${{ steps.build.outputs.ZIP_SHORT_COMMIT_ID }} ${{ steps.build.outputs.ZIP_BUILD_TYPE }} (extract it)"
           path: "${{ steps.build.outputs.ZIP_FOLDER }}/*.zip*"
-          if-no-files-found: "error"
-          retention-days: 10
+          overwrite: false
+          retention-days: "${{ steps.info.outputs.ZIP_RETENTION_DAYS }}"
           compression-level: 0
+          if-no-files-found: "error"
 
   keep-alive:
     name: "Keep alive"
