Minor changes

diff --git a/.github/workflows/auto-release-from-tag.yml b/.github/workflows/auto-release-from-tag.yml
--- a/.github/workflows/auto-release-from-tag.yml
+++ b/.github/workflows/auto-release-from-tag.yml
@@ -19,7 +19,7 @@ jobs:
     name: "Release"
     runs-on: ubuntu-latest
     timeout-minutes: 30
-    if: "${{ startsWith(inputs.tag-name, 'v') || startsWith(github.ref, 'refs/tags/v') }}"
+    if: "${{ inputs.tag-name || startsWith(github.ref, 'refs/tags/v') }}"
     concurrency:
       group: "${{ github.repository_id }}-${{ github.workflow }}-release"
       cancel-in-progress: false
@@ -109,12 +109,33 @@ jobs:
             cp -f -T -- "${old_attest_file:?}" "${new_attest_file:?}" || exit "${?}"
             printf 'ZIP_ATTESTATION_FILE=%s\n' "${new_attest_file:?}" 1>> "${GITHUB_OUTPUT?}"
           fi
+      - name: "Release logic"
+        id: "release-logic"
+        shell: bash
+        run: |
+          # Release logic...
+          CREATE_RELEASE='false'
+          if '${{ github.run_attempt == '1' && steps.build.outputs.ZIP_IS_ALPHA == 'false' && steps.build.outputs.ZIP_BUILD_TYPE_SUPPORTED == 'true' }}'; then
+            CREATE_RELEASE='true'
+          fi
+          printf 'CREATE_RELEASE=%s\n' "${CREATE_RELEASE:?}" 1>> "${GITHUB_OUTPUT?}"
+          printf 'Create release? %s\n' "${CREATE_RELEASE:?}"
+          # Verifying tag name...
+          if '${{ github.event_name == 'workflow_dispatch' && startsWith(inputs.tag-name, 'v') }}'; then # The "workflow_call" event still pass as "workflow_dispatch"
+            TAG_NAME='${{ inputs.tag-name }}'
+          elif '${{ startsWith(github.ref, 'refs/tags/v') }}'; then
+            TAG_NAME='${{ github.ref_name }}'
+          else
+            printf '%s\n' '::error::Invalid "tag-name" parameter: ${{ inputs.tag-name }}'
+            exit 3
+          fi
+          printf 'TAG_NAME=%s\n' "${TAG_NAME:?}" 1>> "${GITHUB_OUTPUT?}"
       - name: "Create release"
         uses: softprops/action-gh-release@v2
-        if: "${{ github.run_attempt == '1' && steps.build.outputs.ZIP_IS_ALPHA == 'false' && steps.build.outputs.ZIP_BUILD_TYPE_SUPPORTED == 'true' }}"
+        if: "${{ steps.release-logic.outputs.CREATE_RELEASE == 'true' }}"
         with:
-          name: "${{ inputs.tag-name || github.ref_name }}"
-          tag_name: "${{ inputs.tag-name || github.ref_name }}"
+          name: "${{ steps.release-logic.outputs.TAG_NAME }}"
+          tag_name: "${{ steps.release-logic.outputs.TAG_NAME }}"
           target_commitish: "${{ github.sha }}"
           body_path: "${{ steps.info.outputs.ZIP_RELEASE_NOTES }}"
           append_body: true
